application: my-app-name
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  upload: index.html
  static_files: index.html

- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images

- url: /elements
  static_dir: elements

- url: /bower_components
  static_dir: bower_components

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)
